import Head from 'next/head';
import PropTypes from 'prop-types';
import styles from "@/styles/Home.module.css";
import { Container } from '@chakra-ui/react';

export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title>{`Create Next App - ${metaTitle}`}</title>
        <meta name="description" content={metaDescription || "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=0.5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Container overflowX="scroll" 
            overflowY="scroll" bg='white' maxW='480px' width="var(--chakra-sizes-full)" mx="auto" px="var(--chakra-space-4)" centerContent>
          {children}
          <Container
            maxHeight="1000px"
          >
            {/* Your content goes here */}
            {children}
            
          </Container>
        </Container>
        {/* <Header /> */}
    </>
  );
};

Layout.propTypes = {
  children: PropTypes.any,
  metaTitle: PropTypes.string,
  metaDescription: PropTypes.string,
};
