import Head from 'next/head';
import PropTypes from 'prop-types';
import { Container } from '@chakra-ui/react';
import Header from '@/components/header';

export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title>{metaTitle}</title>
        <meta name="description" content={metaDescription || "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=0.5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Container bg='white' maxW='480px' width="var(--chakra-sizes-full)" mx="auto" p="0" centerContent>
          <Header />
          <Container
            height='92vh'
            overflowX="scroll" 
            overflowY="scroll"
          >
            {children}
          </Container>
        </Container>
    </>
  );
};

Layout.propTypes = {
  children: PropTypes.any,
  metaTitle: PropTypes.string,
  metaDescription: PropTypes.string,
};
